### PR TITLE
Test rewrite selective check python

### PR DESCRIPTION
**Pull request by edithturn**
TEST of PR

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @edithturn  - > do you want to continue on that one? I think I might want to take a stab on it (also to simplify the logic maybe ) )

**Comment by potiuk** [comment]
I have a feeling It can be somewhat simplified :)

**Comment by edithturn** [comment]
@potiuk of course! I would like it! 👏🏼 😃 
I hope to finish "reuse of build image in python" today (I will send an update in some hours). 
Things are more clear for me now and I think I can re-take "selective check", please let me know how it would be "simplified"

**Comment by potiuk** [comment]
> Things are more clear for me now and I think I can re-take "selective check", please let me know how it would be "simplified"

Not sure yet :).

**Pull request closed without merging**
